name: Continuous Deployment Pipeline

on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: 'build/'
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
